### PR TITLE
fix(l10n): Update Italian translations

### PR DESCRIPTION
**Pull request by chaoscalm**
Proposal to use same naming scheme as used at https://apilevels.com/ for Android Version and SDK level.

### CODE REVIEW

**Comment by chaoscalm** [comment]
I updated the Italian translation, and updated one value in the main values. Good for now.

**Comment by nikclayton** [comment]
Please let me know when you think this is ready for review.

**Comment by chaoscalm** [comment]
@nikclayton In my opinion we are at that level where we are reviewing the cosmetic of the translation inside the U.I., so it is surely reviewable. I am also comparing the translation with other projects like Megalodon and checking with Tusky layout. Some things like the emoji translations appear not working across the various translations. I would like to keep my translation coherent with what other projects will say. But so far yeah it is reviewable.

**Comment by chaoscalm** [comment]
Also my left note for now, I thank you for personally implementing the font Luciole, it seems a very promising font for reading, and I am testing it with pleasure on Pachli, it doesn't stress the eyes at all. And seeing that it was supported by scientific research is a good thing: https://www.sciencedirect.com/science/article/pii/S0001691823001026 Good job!

**Comment by nikclayton** [comment]
OK, thanks for so many updates.

I've pulled the SDK level change in to a separate PR (https://github.com/pachli/pachli-android/pull/211) to keep translation updates separate from changes to the original text.

Just for my own interest (I'm not an Italian speaker), why the change from "menù" to "menu"? Is "menu" more modern?

**Comment by chaoscalm** [comment]
I had that same question together with many others during the process, so I went seeing what other projects were using in Computer Science language: I love integrity through apps when we name a common object:

https://github.com/M66B/FairEmail/blob/master/app/src/main/res/values-it-rIT/strings.xml#L390 Italians call it menu in this project. 

Also based on consulting the Italian dictionary Zanichelli 2024, and most common used terms for computer searches:

**Menù is derived from original word Menu.**

**Comment by chaoscalm** [comment]
Not sure if now is better.

**Comment by nikclayton** [comment]
> Not sure if now is better.

Yeah, this has some regressions that will need to be fixed.

1. The `<?xml...` declaration at the top has been deleted. I think that needs to be put back.
2. There's no need to add/update a copyright block at the top, so that can be removed
3. You've indented all the `<string...` entries by 8 spaces. On casual inspection (without disabling whitespace diffs) this makes it appear as though all the translations have been deleted and replaced.

To fix (3), change all the `        <string...` entries to start with 4 spaces (`    <string...`). This has worked when https://github.com/pachli/pachli-android/pull/206/files shows just the lines that you have changed.

Alternatively, you can enter your translation changes at https://hosted.weblate.org/translate/pachli/ui-strings/it/?q= if that UI is helpful.

Let me know if you've got any questions.

**Pull request closed without merging**
